# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ef04b6460dfe8e18c9e009f8660498ec8bc7d76c470487c348c299e92dd811d16742e1483668f1f31cc086516ed3b2e93cdd2ea28d0ddad8cc57c22ee17d541

test:
  secret_key_base: f12ccca9f7daf59d8955e33de123e5a45b1a25d03ada8915554e620c9d5b49a5959fe9a59f70934671331a8b07548cdd06440865d86d02f2c978107eeb7051ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
